FROM python:3
COPY .  E/CS50projects/CS50WEB/CS50-Web/week7/src7/src7/airline1
WORKDIR E/CS50projects/CS50WEB/CS50-Web/week7/src7/src7/airline1/
RUN pip install -r requirements.txt
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
