# Generated by Django 4.1 on 2022-10-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comment_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bids',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
