# Generated by Django 4.1 on 2022-10-25 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='listing_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_bid', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='bids',
            name='user_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='listing_commnt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_comment', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
