# Generated by Django 4.1 on 2022-10-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bids_bid_bids_listing_bid_bids_user_bid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='listing_commnt',
            new_name='listing_comment',
        ),
    ]
