# Generated by Django 4.1 on 2022-10-25 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_listing_commnt_comment_listing_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listing_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_comment',
        ),
        migrations.DeleteModel(
            name='Bids',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
